### ISSUE TITLE
Wrong Double values 

### ISSUE THREAD

**Issue by vico7** [GaloisInc/sqlite#12]
Hi,

We have found that some Double values get a different value when they are retrieved from the database. 

The following code is an example when the error occurs. 
db  <- openConnection "test.db" 
execStatement db "create table abc (A real);" :: IO (Either String [[Row Value]]) 
execStatement db ("insert into abc (A) values (62.027393);") :: IO (Either String [[Row Value]]) 
table <- execStatement db "select * from abc;"  :: IO (Either String [[Row Value]]) 
print table

The output is: 
62.027393000000004 and in the sqlite3 shell, the values is 62.027393

There are more values which seem to have the same behavior.

It seems that the value is inserted correctly into the table but when it is selected, then the value is slightly different. We looked at your code and found that it is the sqlite3_value_double function in sqlite3_value_value that gives the wrong result. A possible solution is to use the get_text_val function to retrieve the value as a String and then convert it to Double in Haskell. However, we are not sure why the problem occur, if it is the FFI which imports the C function that is the problem or an allocation error but the function seems to work correctly when it is executed in C. 

Best regards
@vico7
@winzor92

**Comment by vico7** [comment]
After some debugging, this seems to be the correct behavior. Sorry for bother you!

**Comment by acw** [comment]
No worries. That's my favorite kind of bug! 😃
