### ISSUE TITLE
Ambiguous occurrence ‘<>’ : Database/SQL/Types.hs:481

### ISSUE THREAD

**Issue by aburn** [GaloisInc/sqlite#13]
Hi,

I'm trying to use this package with stack.

```
stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

I'm seeing the following build failure:

```
.stack-work/downloaded/1h54Xh8hshSY/sqlite-4572cff0640269a7cb65594955fb447556daa7b4/Database/SQL/Types.hs:481:37: error:
        Ambiguous occurrence ‘<>’
        It could refer to either ‘Prelude.<>’,
                                 imported from ‘Prelude’ at Database/SQL/Types.hs:15:8-25
                                 (and originally defined in ‘GHC.Base’)
                              or ‘Text.PrettyPrint.HughesPJ.<>’,
                                 imported from ‘Text.PrettyPrint.HughesPJ’ at Database/SQL/Types.hs:56:1-32

```

I've the following `stack.yaml` config:

```yaml
packages:
- .

extra-deps:
- github: GaloisInc/sqlite
  commit: 4572cff0640269a7cb65594955fb447556daa7b4
```

Is there anything missing in the config. 

For now I just fixed the problem by explicitly `import Prelude hiding ((<>))` or we can  : `Text.PrettyPrint.HughesPJ.<>`  [here](https://github.com/GaloisInc/sqlite/blob/master/Database/SQL/Types.hs#L481).

**Comment by aburn** [comment]
is there an expectation of the GHC version to be used? not sure starting which version `(<>)` was made part of Prelude (if it wasn't from the beginning).

**Comment by acw** [comment]
Hi! I don't know that there's a strong expectation, but that's mostly because we've deprecated this package. Last I checked, [sqlite-simple](https://github.com/nurpax/sqlite-simple) was a good alternative.

I'll merge your patch in shortly, just in case it's helpful, but I'd point you to that project instead.
