### ISSUE TITLE
Types.hs:  Just add a plus sign at line 482 <+> 

### ISSUE THREAD

**Issue by DieGit0** [GaloisInc/sqlite#15]
Hi all, just to know

When trying to run cabal install a compile-time error message was displayed indicating an inconsistency between the current function **<>** and the expected function **<+>** from  Text.PrettyPrint.HughesPJ at line 482  

I guess that was just a typo

So I just extracted the tar.gz file, added the sign [...] and I was able to install the package successfully

------------------------------------------------------------------------------
Source file: sqlite/Database/SQL/Types.hs:                                            
                                                                                                               
FunSQLExpr f es     -> text f **<>** parens (commaH ppSQLExpr es)     
 -----------------------------------------------------------------------------                                                                                                      
My Env:

NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"

cabal-install version 3.6.2.0
compiled using version 3.6.2.0 of the Cabal library

The Glorious Glasgow Haskell Compilation System, version 8.10.7

**Comment by georgefst** [comment]
https://github.com/GaloisInc/sqlite/pull/14 fixes the build (via a slightly different approach). It just hasn't been released to Hackage.
