### ISSUE TITLE
UTF-8 problem

### ISSUE THREAD

**Issue by winzor92** [GaloisInc/sqlite#8]
Hi, 

We think we have found a small bug in the SQLite binding.
More precisely in how the UTF-8 is handled when it is used in Haskell.

We think the problem occurs when we insert a UTF-8 character in the database and then retrieve it from the database. It seems like the character still is in UTF-8 format but it should be in unicode which Haskell uses. 

Here is a code example when the problem occurs:

import Database.SQLite
import qualified Data.ByteString.Char8 as T
import qualified Data.Text as TE
import Data.Text.Encoding (decodeUtf8)

main = do 
     db  <- openConnection "test.db"
     execStatement_ db "create table abc (A text);" :: IO(Maybe String)
     execStatement_ db ("insert into abc (A) values ('º');") :: IO(Maybe String)     
     table <- execStatement db "select * from abc;"  :: IO (Either String [[Row Value]])
     let value =  snd $ head $  concat $ concat $ fromRight table
     putStrLn "º" 
     putStrLn $ getValue value
     putStrLn $ show "º"
     putStrLn $ show $ getValue value
  where fromRight (Right b) = b
        getValue (Text a) = a

The output from the code gives:
º
Âº
"\186"
"\194\186"
where the first two lines should be the same and also the last two lines. 

To solve the problem it is possible to decode the UTF-8 character when it is retrieved from the database. For instance like this:

TE.unpack $ decodeUtf8 (T.pack $ getValue value)

Best regards
@winzor92
@vico7

**Comment by acw** [comment]
Hmmm. OK. I admit that I'm not a UTF expert, but that makes sense. Two questions:

1. Do you have a patch for the problem?
1. Would you be interested in maintaining this software in the future?

**Comment by vico7** [comment]
1. I have tried the Github version of the SQLITE binding and it seems to work correctly. Previously I have tried it with 0.5.2.2 package on hackage and that version seems to have the problem. It might be that the last commit to the git repo fixes the problem.

2. At the moment, we don't feel that we have enough competence in sqlite.

Best regards
@winzor92
@vico7

**Comment by acw** [comment]
OK. 0.5.3 has been pushed to Hackage.
